title: My New Website
author: Mirindi Kabangu
email: mirindikabangu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm not sure what this site is going to be about yet but I'm sure it will be great

# social links
twitter_username: CoolGuyJerome # DO NOT include the @ character, or else the build will fail!
github_username:  MKabangu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
